Reland "Reland "[fx][log] Make fx log call ffx log by default""
This reverts commit c836580e4465be912fe0cfdc0d2051cde4714258.

Reason for revert: https://fxbug.dev/132955 has been fixed.

Fixed: 127491

Original change's description:
> Revert "Reland "[fx][log] Make fx log call ffx log by default""
>
> This reverts commit 8e2432de17208006fb5cb9d910e149ecc49dbac0.
>
> Reason for revert: https://fxbug.dev/132955 still an issue.
>
> Original change's description:
> > Reland "[fx][log] Make fx log call ffx log by default"
> >
> > This reverts commit 7cec7b9d7d5fae2e926dd49bda3caba8a2459f27.
> >
> > Reason for revert: Reland following fxrev.dev/910272
> >
> > Original change's description:
> > > Revert "[fx][log] Make fx log call ffx log by default"
> > >
> > > This reverts commit 16c6a004dcea4c915fc26f5121aeb74f4ee387bd.
> > >
> > > Reason for revert: Mitigation for ffx log breaking change
> > >
> > > Original change's description:
> > > > [fx][log] Make fx log call ffx log by default
> > > >
> > > > Move log_listener-based `fx log` behind `--legacy` and add a
> > > > deprecation warning.
> > > >
> > > > Bug: 131196
> > > > Change-Id: I366efd6059f95beb47f55c6a6f2bf1726d03d64f
> > > > Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/898039
> > > > Reviewed-by: David Turner <digit@google.com>
> > > > Reviewed-by: Miguel Flores <miguelfrde@google.com>
> > > > Reviewed-by: Brian Bosak <bbosak@google.com>
> > > > Commit-Queue: Jay Zhuang <jayzhuang@google.com>
> > >
> > > Bug: 131196
> > > Change-Id: I4646ca944d7ad67f6ff6f53390d0c21d5834cc97
> > > Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/910315
> > > Reviewed-by: RubberStamper 🤖 <android-build-ayeaye@system.gserviceaccount.com>
> > > Commit-Queue: Christopher Johnson <crjohns@google.com>
> >
> > Bug: 131196
> > Change-Id: I50356c3406a2c9e7daa2d4921eda24c2896e90ed
> > Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/910317
> > Reviewed-by: RubberStamper 🤖 <android-build-ayeaye@system.gserviceaccount.com>
> > Commit-Queue: Christopher Johnson <crjohns@google.com>
>
> Bug: 131196
> Change-Id: Iffe43132ed962bfc3d81954905a7086af8c745f5
> No-Presubmit: true
> No-Tree-Checks: true
> No-Try: true
> Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/910894
> Commit-Queue: Brian Bosak <bbosak@google.com>
> Reviewed-by: RubberStamper 🤖 <android-build-ayeaye@system.gserviceaccount.com>

Bug: 131196
Change-Id: I8f816d8667c65c1a3516299bac01ede8804dca65
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/914313
Reviewed-by: David Turner <digit@google.com>
Reviewed-by: Christopher Johnson <crjohns@google.com>
Reviewed-by: Oliver Newman <olivernewman@google.com>
Reviewed-by: Miguel Flores <miguelfrde@google.com>
Commit-Queue: Brian Bosak <bbosak@google.com>

diff --git a/tools/devshell/log b/tools/devshell/log
--- a/tools/devshell/log
+++ b/tools/devshell/log
@@ -4,9 +4,18 @@
 # found in the LICENSE file.
 
 #### CATEGORY=Run, inspect and debug
-### listen for logs from the on-device log_listener
+### Display logs from a target device.
 
-## usage: fx log [-h | --help] [--raw] [-r | --remote-symbols] LOG_LISTENER_FLAGS
+## usage: fx log FFX_LOG_FLAGS
+##
+##    FFX_LOG_FLAGS           flags to pass to ffx log, see `fx ffx log --help`.
+##
+## LEGACY MODE: listen for logs from the on-device log_listener
+##
+## usage: fx log --legacy [-h | --help] [--raw] LOG_LISTENER_FLAGS
+##
+##    --legacy                runs in legacy mode, i.e. listen for logs from
+##                            the on-device log_listener
 ##
 ##    --raw                   do not attempt to symbolize the log
 ##
@@ -31,49 +40,59 @@ set -o pipefail
 
 source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/lib/vars.sh || exit $?
 
-function listen {
-  while true; do
-    fx-command-run wait || return
-    fx-command-run shell log_listener "$@"
-    local error_code=$?
-    if [[ "${error_code}" -eq 0 ]]; then
-      # this is necessary, so that "--dump_logs yes" works as expected.
-      break
-    fi
-    echo "$(date '+%Y-%m-%d %H:%M:%S %Z'): Connection lost (status ${error_code}), reconnecting..."
-  done
-}
-
-declare is_raw=0
-declare symbolizer=( "fx-command-run" "ffx" "debug" "symbolize" )
-
-while [[ $# -ne 0 ]]; do
-  case "$1" in
-  -h|--help)
-    fx-command-help
-    echo
-    echo "[Attempting to shell into a connected device to provide help for the on-device log_listener]"
-    fx-command-exec shell log_listener -h
-    exit 0
-    ;;
-  --raw)
-    is_raw=1
-    ;;
-  --remote-symbols|-r)
-    fx-error "--remote-symbols|-r is deprecated. Remote symbolization will be tried automatically."
-    exit 1
-    ;;
-  --no-prettify)
-    symbolizer+=("--no-prettify")
-    ;;
-  *)
-    break
-  esac
+if [[ "$1" == '--legacy' ]]; then
   shift
-done
 
-if (( is_raw )); then
-  listen "$@"
+  fx-warn 'DEPRECATION WARNING'
+  fx-warn 'You are using `fx log` in legacy mode, this mode will be removed soon.'
+  fx-warn 'If you have any concerns, please report to https://fxbug.dev/131196.\n'
+
+  function listen {
+    while true; do
+      fx-command-run wait || return
+      fx-command-run shell log_listener "$@"
+      local error_code=$?
+      if [[ "${error_code}" -eq 0 ]]; then
+        # this is necessary, so that "--dump_logs yes" works as expected.
+        break
+      fi
+      echo "$(date '+%Y-%m-%d %H:%M:%S %Z'): Connection lost (status ${error_code}), reconnecting..."
+    done
+  }
+
+  declare is_raw=0
+  declare symbolizer=( "fx-command-run" "ffx" "debug" "symbolize" )
+
+  while [[ $# -ne 0 ]]; do
+    case "$1" in
+    -h|--help)
+      fx-command-help
+      echo
+      echo "[Attempting to shell into a connected device to provide help for the on-device log_listener]"
+      fx-command-exec shell log_listener -h
+      exit 0
+      ;;
+    --raw)
+      is_raw=1
+      ;;
+    --remote-symbols|-r)
+      fx-error "--remote-symbols|-r is deprecated. Remote symbolization will be tried automatically."
+      exit 1
+      ;;
+    --no-prettify)
+      symbolizer+=("--no-prettify")
+      ;;
+    *)
+      break
+    esac
+    shift
+  done
+
+  if (( is_raw )); then
+    listen "$@"
+  else
+    listen "$@" | "${symbolizer[@]}"
+  fi
 else
-  listen "$@" | "${symbolizer[@]}"
+  fx-command-run ffx log "$@"
 fi
