[fx][ota] Check TUF metadata for base package merkle
This checks the TUF metadata for the base package merkle, rather than
reading a build artifact. This allows this command to work with the
GN/Bazel built products.

Change-Id: I4b803acf6354c8553b7f6bf57fe47f017dfcb709
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/830718
Reviewed-by: Andrew Pollack <andrewpollack@google.com>
Fuchsia-Auto-Submit: Erick Tryzelaar <etryzelaar@google.com>
Reviewed-by: Oliver Newman <olivernewman@google.com>
Commit-Queue: Auto-Submit <auto-submit@fuchsia-infra.iam.gserviceaccount.com>

diff --git a/tools/devshell/ota b/tools/devshell/ota
--- a/tools/devshell/ota
+++ b/tools/devshell/ota
@@ -26,8 +26,30 @@ source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/lib/updat
 fx-config-read
 
 function needs-update {
-  local system_image_merkle="${FUCHSIA_BUILD_DIR}"/obj/build/images/fuchsia/fuchsia/base/base.merkle
-  [[ $(fx-command-run shell 'read ver < /system/meta;echo $ver') != $(<"${system_image_merkle}") ]]
+  local targets_path="${FUCHSIA_BUILD_DIR}/amber-files/repository/targets.json"
+  local base_package="system_image/0"
+  local jq_filter=".signed.targets[\"${base_package}\"].custom.merkle"
+  local base_package_merkle
+
+  if [ ! -e "${targets_path}" ]; then
+    fx-error "TUF targets metadata '${targets_path}' does not exist."
+    fx-error "You may need to run 'fx build' to create it."
+    return 1
+  fi
+
+  if ! base_package_merkle=$(fx-command-run jq -e -r "$jq_filter" "$targets_path"); then
+    fx-error "TUF targets metadata does not contain the packge '${base_package}'".
+    fx-error "You may need to run 'fx build' to create it."
+    return 1
+  fi
+
+  if [[ "${base_package_merkle}" == "" || "${base_package_merkle}" == "null" ]]; then
+    fx-error "Invalid merkle for TUF targets entry for 'system_image/0'."
+    fx-error "Merkle must be a non-empty string, not '${base_package_merkle}'."
+    return 1
+  fi
+
+  [[ $(fx-command-run shell 'read ver < /system/meta;echo $ver') != "${base_package_merkle}" ]]
 }
 
 function target-using-omaha-client {
