[swd][fx] fx serve
Serves ffx-based repository and registration process
in the foreground

fx --enable=foreground_repo_server serve

Change-Id: I8cc1f3d869cf4449c47e80560abd75092f75e81e
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/911972
Fuchsia-Auto-Submit: Andrew Pollack <andrewpollack@google.com>
Commit-Queue: Auto-Submit <auto-submit@fuchsia-infra.iam.gserviceaccount.com>
Reviewed-by: Erick Tryzelaar <etryzelaar@google.com>
Reviewed-by: Oliver Newman <olivernewman@google.com>

diff --git a/tools/devshell/serve b/tools/devshell/serve
--- a/tools/devshell/serve
+++ b/tools/devshell/serve
@@ -18,14 +18,18 @@
 ##   --name NAME        Name the generated update source config NAME.
 ##   --[no-]persist     enable or disable persistence of repository metadata. Disabled
 ##                      by default.
-##   -v                 verbose mode, shows info and debug messages from "pm"
+##   -v                 verbose mode, shows info and debug messages from "pm" and "ffx repository serve"
 ##   -C|--clean         clean the package repository first. This flag is only
 ##                      valid if the incremental package publishing is enabled.
 ##
-## This command supports incremental package publishing. If enabled, it will
-## auto-publish packages as they are created or modified.
+## This command supports:
+##  - incremental package publishing. If enabled, it will auto-publish packages as they
+##    are created or modified.
+##  - foreground repository serving. If enabled, the repository server and device registration
+##    flows will be ran as a foreground process.
 ##
 ## To enable incremental package serving, run "fx --enable=incremental serve ..."
+## To enable foreground repository serving, run "fx --enable=foreground_repo_server serve ..."
 
 source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/lib/vars.sh || exit $?
 source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/lib/updates.sh || exit $?
@@ -225,12 +229,14 @@ else
   fi
 fi
 
-if [[ "${server_mode}" = "pm" ]]; then
-  # Default the port to 8083 if it is unset.
+# Default the port to 8083 if it is unset.
+if [[ "${server_mode}" = "pm" ]] || is_feature_enabled "foreground_repo_server"; then
   if [[ -z "${port}" ]]; then
     port="8083"
   fi
+fi
 
+if [[ "${server_mode}" = "pm" ]]; then
   pm_serve_args=( serve -vt -repo "${repo_dir}" "${pm_serve_flags[@]}" )
 
   # the manifest list file has relative paths and "pm serve" looks for them
@@ -287,22 +293,6 @@ if [[ "${server_mode}" = "pm" ]]; then
     exit $err
   fi
 else
-  ffx-start-server "" "${port}"
-  err=$?
-  if [[ "${err}" -ne 0 ]]; then
-    exit "${err}"
-  fi
-
-  ffx_server_started=1
-
-  if [[ "${verbose}" == true ]]; then
-    # FIXME(http://fxbug.dev/78891): `ffx daemon log` doesn't have a mechanism for
-    # filtering based off of a specific tag, so we'll grep for the lines that
-    # denote traffic to the web server.
-    fx-command-run ffx daemon log --follow --line-count 0 | grep ' \(fuchsia_repo::server\)\|\(ffx_daemon_service_repo\): ' &
-    pm_pid=$!
-  fi
-
   if is_feature_enabled "incremental" || is_feature_enabled "incremental_new"; then
     fx-info "Incremental package auto-publishing is enabled for ffx."
     package_tool_flags=(
@@ -349,98 +339,116 @@ if [[ ! -e "${FUCHSIA_BUILD_DIR}/ssh-keys/ssh_config" ]]; then
   fx-warn "Then re-run this command."
 fi
 
-log "Discovery..."
-
-# State is used to prevent too much output
-state="discover"
-
-# Keep track if we reported any discovery failures
-reported_discovery_failed=0
-
-# exponential backoff in seconds.
-backoff=1
-while true; do
-  if [[ -n "${pm_pid}" ]]; then
-    if ! kill -0 "${pm_pid}" 2> /dev/null; then
-      log "Server died, exiting"
-      pm_pid=
-      exit 1
-    fi
+if is_feature_enabled "foreground_repo_server"; then
+  ffx_flags=( --config repository.foreground.enabled=true )
+  if [[ "${verbose}" == true ]]; then
+    ffx_flags+=( -v )
   fi
 
-  if [[ "${state}" == "discover" ]]; then
-    # While we're still trying to connect to the device, clear the target
-    # address state so we re-resolve.
-    clear-target-addr
-    with-pinned-target fx-command-run shell exit 2>/dev/null
-    ping_result=$?
+  if [[ -z "${source_name}" ]]; then
+    source_name="$(ffx-default-repository-name)"
+  fi
 
-    if [[ "${ping_result}" == 0 ]]; then
-      log "Device up"
-      reported_discovery_failed=0
-      backoff=1
-      state="config"
-    elif [[ "${reported_discovery_failed}" == 0 ]]; then
-      reported_discovery_failed=1
+  fx-command-run ffx ${ffx_flags[@]} repository serve \
+    --address [::]:${port} \
+    --repository "${source_name}" \
+    --alias "fuchsia.com" \
+    --alias "chromium.org"
+else
+  # Legacy serving... pm and background ffx
+  log "Discovery..."
 
-      # Log if we don't know the device's address yet, or if we don't have a device configured.
-      device_addr="$(get-fuchsia-device-addr 2>/dev/null)"
-      if [[ -z "${device_addr}" ]]; then
-        device_name="$(get-device-name 2>/dev/null)"
-        if [[ -n "${device_name}" ]]; then
-          log "Trying to resolve '${device_name}'..."
+  # State is used to prevent too much output
+  state="discover"
+
+  # Keep track if we reported any discovery failures
+  reported_discovery_failed=0
+
+  # exponential backoff in seconds.
+  backoff=1
+  while true; do
+    if [[ -n "${pm_pid}" ]]; then
+      if ! kill -0 "${pm_pid}" 2> /dev/null; then
+        log "Server died, exiting"
+        pm_pid=
+        exit 1
+      fi
+    fi
+
+    if [[ "${state}" == "discover" ]]; then
+      # While we're still trying to connect to the device, clear the target
+      # address state so we re-resolve.
+      clear-target-addr
+      with-pinned-target fx-command-run shell exit 2>/dev/null
+      ping_result=$?
+
+      if [[ "${ping_result}" == 0 ]]; then
+        log "Device up"
+        reported_discovery_failed=0
+        backoff=1
+        state="config"
+      elif [[ "${reported_discovery_failed}" == 0 ]]; then
+        reported_discovery_failed=1
+
+        # Log if we don't know the device's address yet, or if we don't have a device configured.
+        device_addr="$(get-fuchsia-device-addr 2>/dev/null)"
+        if [[ -z "${device_addr}" ]]; then
+          device_name="$(get-device-name 2>/dev/null)"
+          if [[ -n "${device_name}" ]]; then
+            log "Trying to resolve '${device_name}'..."
+          else
+            log "Either no device or multiple devices are discoverable. Run 'fx list-devices' and if necessary run 'fx set-device'."
+          fi
         else
-          log "Either no device or multiple devices are discoverable. Run 'fx list-devices' and if necessary run 'fx set-device'."
+          log "Trying to connect to ${device_addr}..."
         fi
+      fi
+
+      if [[ "${ping_result}" != 0 ]]; then
+        sleep "${backoff}"
+        backoff=$(( $backoff * 2 ))
+        if [[ "${backoff}" -gt 10 ]]; then
+          backoff=10
+        fi
+      fi
+    else
+      with-pinned-target fx-command-run shell -O check > /dev/null 2>&1
+      ping_result=$?
+    fi
+
+    if [[ "${state}" == "config" ]]; then
+      log "Registering devhost as update source"
+
+      add_update_source_args=( "${persist}" --port "${port}" --server-mode "${server_mode}" )
+      if [[ ! -z "${source_name}" ]]; then
+        add_update_source_args+=( --name "${source_name}" )
+      fi
+
+      if with-pinned-target fx-command-run add-update-source "${add_update_source_args[@]}"; then
+        log "Ready to push packages!"
+        # Log the uptime so that it is clear(er) from fx serve if the device rebooted.
+        # The tr is present as the output sometimes contains spurious control characters.
+        clock=$(with-pinned-target fx-command-run shell clock --monotonic)
+        if [[ -n ${clock} ]]; then
+          uptime=$(echo $clock | tr '[[:cntrl:]]' ' ' )
+          log "Target uptime: $(( $uptime / 1000000000 ))"
+        fi
+        state="ready"
       else
-        log "Trying to connect to ${device_addr}..."
+        log "Device lost while configuring update source"
+        state="discover"
       fi
     fi
 
-    if [[ "${ping_result}" != 0 ]]; then
-      sleep "${backoff}"
-      backoff=$(( $backoff * 2 ))
-      if [[ "${backoff}" -gt 10 ]]; then
-        backoff=10
+    if [[ "${state}" == "ready" ]]; then
+      if [[ "${ping_result}" != 0 ]]; then
+        log "Device lost"
+        state="discover"
+      else
+        sleep 1
       fi
     fi
-  else
-    with-pinned-target fx-command-run shell -O check > /dev/null 2>&1
-    ping_result=$?
-  fi
-
-  if [[ "${state}" == "config" ]]; then
-    log "Registering devhost as update source"
-
-    add_update_source_args=( "${persist}" --port "${port}" --server-mode "${server_mode}" )
-    if [[ ! -z "${source_name}" ]]; then
-      add_update_source_args+=( --name "${source_name}" )
-    fi
-
-    if with-pinned-target fx-command-run add-update-source "${add_update_source_args[@]}"; then
-      log "Ready to push packages!"
-      # Log the uptime so that it is clear(er) from fx serve if the device rebooted.
-      # The tr is present as the output sometimes contains spurious control characters.
-      clock=$(with-pinned-target fx-command-run shell clock --monotonic)
-      if [[ -n ${clock} ]]; then
-        uptime=$(echo $clock | tr '[[:cntrl:]]' ' ' )
-        log "Target uptime: $(( $uptime / 1000000000 ))"
-      fi
-      state="ready"
-    else
-      log "Device lost while configuring update source"
-      state="discover"
-    fi
-  fi
-
-  if [[ "${state}" == "ready" ]]; then
-    if [[ "${ping_result}" != 0 ]]; then
-      log "Device lost"
-      state="discover"
-    else
-      sleep 1
-    fi
-  fi
-done
+  done
+fi
 
 # See EXIT trap above for cleanup that occurs
