[swd][fx] fx serve resilient foreground
When target is lost, `fx serve` will now end the current foreground
process, and re-do the repo start/registration workflow.

Additionally, we now run a check for "foreground_repo_server" as
part of the state==config state machine, as opposed to an entirely
separate if/else.

Lastly, cleanup will now properly close the foreground repo
server, using passed PID.

Fixed: b/300264230
Change-Id: I8c2ca94a084cdafc83001b62d48457aa479a5fbe
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/916436
Reviewed-by: Erick Tryzelaar <etryzelaar@google.com>
Commit-Queue: Andrew Pollack <andrewpollack@google.com>

diff --git a/tools/devshell/serve b/tools/devshell/serve
--- a/tools/devshell/serve
+++ b/tools/devshell/serve
@@ -109,6 +109,7 @@ fi
 pm_pid=
 package_tool_pid=
 ffx_server_started=
+foreground_repo_server_pid=
 cleanup() {
   if [[ -n "${package_tool_pid}" ]]; then
     if kill -0 "${package_tool_pid}" 2> /dev/null; then
@@ -124,6 +125,12 @@ cleanup() {
       fi
     fi
   else
+    if [[ -n "${foreground_repo_server_pid}" ]]; then
+      if kill -0 "${foreground_repo_server_pid}" 2> /dev/null; then
+        kill -TERM "${foreground_repo_server_pid}" 2> /dev/null
+        wait "${foreground_repo_server_pid}" 2> /dev/null
+      fi
+    fi
     if [[ ! -z "${ffx_server_started}" ]]; then
       ffx-stop-server
     fi
@@ -339,86 +346,88 @@ if [[ ! -e "${FUCHSIA_BUILD_DIR}/ssh-keys/ssh_config" ]]; then
   fx-warn "Then re-run this command."
 fi
 
-if is_feature_enabled "foreground_repo_server"; then
-  ffx_flags=( --config repository.foreground.enabled=true )
-  if [[ "${verbose}" == true ]]; then
-    ffx_flags+=( -v )
-  fi
+log "Discovery..."
 
-  if [[ -z "${source_name}" ]]; then
-    source_name="$(ffx-default-repository-name)"
-  fi
+# State is used to prevent too much output
+state="discover"
 
-  fx-command-run ffx ${ffx_flags[@]} repository serve \
-    --address [::]:${port} \
-    --repository "${source_name}" \
-    --alias "fuchsia.com" \
-    --alias "chromium.org"
-else
-  # Legacy serving... pm and background ffx
-  log "Discovery..."
+# Keep track if we reported any discovery failures
+reported_discovery_failed=0
 
-  # State is used to prevent too much output
-  state="discover"
-
-  # Keep track if we reported any discovery failures
-  reported_discovery_failed=0
-
-  # exponential backoff in seconds.
-  backoff=1
-  while true; do
-    if [[ -n "${pm_pid}" ]]; then
-      if ! kill -0 "${pm_pid}" 2> /dev/null; then
-        log "Server died, exiting"
-        pm_pid=
-        exit 1
-      fi
+# exponential backoff in seconds.
+backoff=1
+while true; do
+  if [[ -n "${pm_pid}" ]]; then
+    if ! kill -0 "${pm_pid}" 2> /dev/null; then
+      fx-error "Server died, exiting"
+      pm_pid=
+      exit 1
     fi
+  fi
 
-    if [[ "${state}" == "discover" ]]; then
-      # While we're still trying to connect to the device, clear the target
-      # address state so we re-resolve.
-      clear-target-addr
-      with-pinned-target fx-command-run shell exit 2>/dev/null
-      ping_result=$?
+  if [[ "${state}" == "discover" ]]; then
+    # While we're still trying to connect to the device, clear the target
+    # address state so we re-resolve.
+    clear-target-addr
+    with-pinned-target fx-command-run shell exit 2>/dev/null
+    ping_result=$?
 
-      if [[ "${ping_result}" == 0 ]]; then
-        log "Device up"
-        reported_discovery_failed=0
-        backoff=1
-        state="config"
-      elif [[ "${reported_discovery_failed}" == 0 ]]; then
-        reported_discovery_failed=1
+    if [[ "${ping_result}" == 0 ]]; then
+      log "Device up"
+      reported_discovery_failed=0
+      backoff=1
+      state="config"
+    elif [[ "${reported_discovery_failed}" == 0 ]]; then
+      reported_discovery_failed=1
 
-        # Log if we don't know the device's address yet, or if we don't have a device configured.
-        device_addr="$(get-fuchsia-device-addr 2>/dev/null)"
-        if [[ -z "${device_addr}" ]]; then
-          device_name="$(get-device-name 2>/dev/null)"
-          if [[ -n "${device_name}" ]]; then
-            log "Trying to resolve '${device_name}'..."
-          else
-            log "Either no device or multiple devices are discoverable. Run 'fx list-devices' and if necessary run 'fx set-device'."
-          fi
+      # Log if we don't know the device's address yet, or if we don't have a device configured.
+      device_addr="$(get-fuchsia-device-addr 2>/dev/null)"
+      if [[ -z "${device_addr}" ]]; then
+        device_name="$(get-device-name 2>/dev/null)"
+        if [[ -n "${device_name}" ]]; then
+          log "Trying to resolve '${device_name}'..."
         else
-          log "Trying to connect to ${device_addr}..."
+          log "Either no device or multiple devices are discoverable. Run 'fx list-devices' and if necessary run 'fx set-device'."
         fi
+      else
+        log "Trying to connect to ${device_addr}..."
       fi
-
-      if [[ "${ping_result}" != 0 ]]; then
-        sleep "${backoff}"
-        backoff=$(( $backoff * 2 ))
-        if [[ "${backoff}" -gt 10 ]]; then
-          backoff=10
-        fi
-      fi
-    else
-      with-pinned-target fx-command-run shell -O check > /dev/null 2>&1
-      ping_result=$?
     fi
 
-    if [[ "${state}" == "config" ]]; then
-      log "Registering devhost as update source"
+    if [[ "${ping_result}" != 0 ]]; then
+      sleep "${backoff}"
+      backoff=$(( $backoff * 2 ))
+      if [[ "${backoff}" -gt 10 ]]; then
+        backoff=10
+      fi
+    fi
+  else
+    with-pinned-target fx-command-run shell -O check > /dev/null 2>&1
+    ping_result=$?
+  fi
 
+  if [[ "${state}" == "config" ]]; then
+    log "Registering devhost as update source"
+
+    if is_feature_enabled "foreground_repo_server"; then
+      ffx_flags=( --config repository.foreground.enabled=true )
+      if [[ "${verbose}" == true ]]; then
+        ffx_flags+=( -v )
+      fi
+
+      if [[ -z "${source_name}" ]]; then
+        source_name="$(ffx-default-repository-name)"
+      fi
+
+      fx-command-exec ffx ${ffx_flags[@]} repository serve \
+        --address [::]:${port} \
+        --repository "${source_name}" \
+        --alias "fuchsia.com" \
+        --alias "chromium.org" &
+      foreground_repo_server_pid=$!
+
+      state="ready"
+    else
       add_update_source_args=( "${persist}" --port "${port}" --server-mode "${server_mode}" )
       if [[ ! -z "${source_name}" ]]; then
         add_update_source_args+=( --name "${source_name}" )
@@ -439,16 +448,35 @@ else
         state="discover"
       fi
     fi
+  fi
 
-    if [[ "${state}" == "ready" ]]; then
-      if [[ "${ping_result}" != 0 ]]; then
-        log "Device lost"
-        state="discover"
-      else
-        sleep 1
+  if [[ "${state}" == "ready" ]]; then
+    # Check if foreground repo ever goes down.
+    if [[ -n "${foreground_repo_server_pid}" ]]; then
+      if ! kill -0 "${foreground_repo_server_pid}" 2> /dev/null; then
+        fx-error "Foreground server exited unexpectedly. Please retry."
+        foreground_repo_server_pid=
+        exit 1
       fi
     fi
-  done
-fi
+
+    if [[ "${ping_result}" != 0 ]]; then
+      log "Device lost"
+
+      # Ensure foreground repo session stops before spinning another.
+      if [[ -n "${foreground_repo_server_pid}" ]]; then
+        if kill -0 "${foreground_repo_server_pid}" 2> /dev/null; then
+          kill -TERM "${foreground_repo_server_pid}" 2> /dev/null
+          wait "${foreground_repo_server_pid}" 2> /dev/null
+        fi
+        foreground_repo_server_pid=
+      fi
+
+      state="discover"
+    else
+      sleep 1
+    fi
+  fi
+done
 
 # See EXIT trap above for cleanup that occurs
