[devshell] update-if-in-base supports json-formatted package lists
Package lists were changed from line-oriented to json-formatted, but
this script was not updated.

Bug: 130443
Change-Id: Idb05c859f03bca3d1434804b9c162cb6fbf2f1b8
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/883218
Reviewed-by: Oliver Newman <olivernewman@google.com>
Commit-Queue: Auto-Submit <auto-submit@fuchsia-infra.iam.gserviceaccount.com>
Fuchsia-Auto-Submit: Ben Keller <galbanum@google.com>
Reviewed-by: Erick Tryzelaar <etryzelaar@google.com>

diff --git a/tools/devshell/update-if-in-base b/tools/devshell/update-if-in-base
--- a/tools/devshell/update-if-in-base
+++ b/tools/devshell/update-if-in-base
@@ -20,7 +20,25 @@ fx-config-read
 
 # Determine if the given package name is in the base package list
 function is-in-base {
-  grep "^$1$" "${FUCHSIA_BUILD_DIR}/base_packages.list" > /dev/null
+  # In base_packages.list, content.manifests is an array of paths. This query returns the string
+  # "true" if the final segment of any of the paths is equal to $1, otherwise it returns the string
+  # "false".
+  local query=".content .manifests | map(. / \"/\" | .[-1]) | index(\"$1\") != null"
+  local present=$(fx-command-run jq "$query" "${FUCHSIA_BUILD_DIR}/base_packages.list")
+
+  local err=$?
+  if [[ $err -ne 0 ]]; then
+    fx-error "Unable to parse the base package list: ${FUCHSIA_BUILD_DIR}/base_packages.list"
+    return err
+  fi
+
+  case "$present" in
+    "true") return 0 ;;
+    "false") return 1 ;;
+    *)
+      fx-error "Unexpected output parsing base package list: $present"
+      return 2
+  esac
 }
 
 function main {
